# This is a basic workflow to help you get started with Actions

name: Sync tengxun

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

# 在仓库内定义了三个环境变量: GUANGDONG_PRIVATE_KEY  MY_DOMAIN  MY_USER
env:
  MY_DOMAIN: 42.193.219.174
  MY_USER: root
  remote_dir: /root/kkkk
jobs:
  # This workflow contains a single job called "build"
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: tar.gz , Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GUONEI_KEY }}"
          mkdir -p ~/.ssh
          ssh-keyscan $MY_DOMAIN >> ~/.ssh/known_hosts

      - name: fstp install
        run: |
          sudo apt install lftp 
          echo "\n==================\n"
          tar -zcf aaa.tar.gz ./*
          echo "\n=====成功创建=====\n"
      - name: ssh connect
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "\n================================\n"
          ssh $MY_USER@$MY_DOMAIN "rm -rf $remote_dir && mkdir $remote_dir "
          scp aaa.tar.gz $MY_USER@$MY_DOMAIN:$remote_dir
          ssh $MY_USER@$MY_DOMAIN "cd $remote_dir && tar -zxf aaa.tar.gz  && rm -rf aaa.tar.gz "



