# This is a basic workflow to help you get started with Actions

name: Sync tengxun

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

# 在仓库内定义了三个环境变量: GUANGDONG_PRIVATE_KEY  MY_DOMAIN  MY_USER

jobs:
  # This workflow contains a single job called "build"
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 第一步: 配置
      - name: show pwd
        with:
          persist-credentials: false
          fetch-depth: 0
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "\n==================\n"
          pwd
          ls
          tar zcvf aaa.tar.gz ./*
          ls
          echo "\n=====成功创建=====\n"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GUONEI_KEY }}"
      - name: ssh connect
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "\n========shhhhhh==========\n"
          ssh root@42.193.219.174
          ls